### ISSUE TITLE
Atticus the Primogenitor [Spoilers]

### ISSUE THREAD

**Issue by Erumite** [Haplo064/ChatBubbles#63]
The S-Rank in Heritage Found will use chat bubbles above each of his 3 heads to indicate which direction he'll be attacking in with his breath attack.

When Chat Bubbles is enabled, all of the bubbles appear on the central head which makes the telegraph impossible to resolve without disabling the plugin.

```
[10:06]Atticus the Primogenitor: If three heads do not sssuffice, you shall face the ssstrength of sssix!
[10:06]Atticus the Primogenitor: Dessstroy...
[10:06]Atticus the Primogenitor: Combination...
[10:06]Atticus the Primogenitor: Breath?
[10:06]Atticus the Primogenitor: To sssmithereens...
[10:06]Atticus the Primogenitor: Burssst...
```

**Comment by MKhayle** [comment]
hello! I have only reached that area today and the only time it spawned when I was there, it was on the half of the map I couldn't access

I will fix this in due time!

**Comment by bethsmoothmove** [comment]
This issue is also present with [this](https://github.com/PunishedPineapple/WhatDidYouSay) other plugin; I raised the issue there but if you know what is causing the problem that might help them too!

**Comment by PunishedPineapple** [comment]
FWIW, it seems like the open chat bubble delegate definition is missing an Int32 parameter at the end.  I come up with `( IntPtr pThis, GameObject* pActor, IntPtr pString, byte param3, Int32 param4 )`.  Unfortuantely, I cannot find an easily accessible enemy or other NPC with which to test whether this resolves the issue.  Also don't think that that function actually returns anything from what I can tell, but that part probably doesn't really matter since it's just passing it straight through.

**Comment by MKhayle** [comment]
it does look like a "novelty" feature was added in that delegate, my guess would be that param4 is the bone it's attached to but idk how to handle this

**Comment by MKhayle** [comment]
(it's fixed btw)
